apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authkit.fullname" . }}-config
  labels:
    {{- include "authkit.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.nodeEnv | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  BASE_URL: {{ .Values.env.baseUrl | quote }}
  PORT: "3001"
  HOST: "0.0.0.0"
